FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY k8s-middleware/go.mod k8s-middleware/go.sum ./
RUN go mod download

COPY k8s-middleware/ ./

RUN go build -o k8s-middleware .

FROM alpine:latest

WORKDIR /app

RUN mkdir -p /root/.kube

COPY --from=builder /app/k8s-middleware .

EXPOSE 3001

CMD ["./k8s-middleware"]
